#port
server:
  port: 9090
  shutdown: graceful
#MVC
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:oracle:thin:@211.238.142.22:1521:XE
    username: hr
    password: happy
    driver-class-name: oracle.jdbc.driver.OracleDriver
#MyBatis
mybatis:
  type-aliases-package: com.sist.web.vo
  mapper-locations: mybatis/mapper/*.xml

menagement:
  endpoints:
    web:
      exposure:
        include: health
  endpoins:
    health:
      show-details: always 